import "./globals.css";

export const metadata = {
  title: "物理学習マップ（剛体にはたらく力）",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body>{children}</body>
    </html>
  );
}
